CREATE TABLE person (
    chat_id bigint PRIMARY KEY,
    first_name varchar(100),
    last_name varchar(100),
    user_name varchar(100),
    registered_at timestamptz
);

CREATE TABLE event (
    event_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(200),
    description varchar(500),
    seats int,
    date_of_event timestamptz
);

CREATE TABLE person_event (
    chat_id bigint REFERENCES person(chat_id),
    event_id bigint REFERENCES event(event_id),
    PRIMARY KEY (chat_id, event_id)
)